name: Publish NuGet Package to Azure Artifacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        source-url: ${{ secrets.AZURE_FEED }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_PAT }}
    
    - name: Restore dependencies
      run: dotnet restore ./Snowflake.Data/Snowflake.Data.csproj

    - name: Build project
      run: dotnet build ./Snowflake.Data/Snowflake.Data.csproj --configuration Release

    - name: Pack NuGet package
      run: dotnet pack ./Snowflake.Data/Snowflake.Data.csproj  --output ./nupkg --configuration Release -p:PackageId=Loome.Snowflake.Data

    - name: Push package to Azure Artifacts
      run: dotnet nuget push ./nupkg/*.nupkg --api-key AzureDevOps --source ${{ secrets.AZURE_FEED }}
